MODEL_NAME: "bart"
PRETRAINED_PATH: "facebook/bart-base"
MODEL_WEIGHTS: "model/tage_bart.pt"

TASK_FILE: "configs/tasks.txt"
ARG_FILE: "configs/args.txt"
GND_FILE: "configs/grounding.txt"

TRAIN_DATA_FILE: "data/train.csv"
DEV_DATA_FILE: "data/dev.csv"
TEST_DATA_FILE: "data/test.csv"

BATCH_SIZE: 8
NUM_BEAMS: 1
MIN_LENGTH: 0
MAX_LENGTH: 100